### ISSUE TITLE
test on very large fq file

### ISSUE THREAD

**Issue by dougwyu** [PaulGreenfieldOz/WorkingDogs#12]
Hi.  i had an idea to try Kelpie on a 1.4 GB fastq file.  

I have several fastq files of shotgun-sequenced samples of arthropods, and i used FilterReads to filter in reads that match an *.mer file made with BuildFilter from the Barcode of Life arthropod barcodes.  This part was fast.

I then concatenated all the filtered fq files and started to run Kelpie on them. The idea is that this would maximise the number of recovered barcode sequences, since any individual fq file likely doesn't have enough reads to assemble across many of the barcodes. Then, i would later map the read pairs from each sample fq file to the kelpie-assembled set of barcodes. This should improve species detection because it is not necessary to fully map a barcode in order to infer the presence of that barcode in a sample (in fact, only about 50% coverage is needed to get confident detection).

I set Kelpie running a week ago, and it has not finished.  I appreciate that Kelpie wasn't designed for huge input files, but i think this protocol would greatly increase Kelpie's usefulness. We spent a long time building our barcode database, involving a lot of collecting and individual barcoding, but if one could just start with the samples themselves and use Kelpie to pull out a reference set of barcodes., then a barrier to entry would be removed.  

Doug

Here are the output messages so far:

built kMer sets from forward primer
built kMer sets from reverse primer
filtering /gpfs/home/b042/ArcDyn_tutorial/arthmito_filtered_files/PlatesGH_all_arthmito.fq
found 221845 reads matching starting/terminating primers
initial starting filter contains 8476029 kMers
initial ending filter contains 1426 kMers

final starting filter contains 3151497 kMers
final ending filter contains 1426 kMers
filtered and kept 3729834/4671185 primer-region reads from 1 files in 446.5s
built terminating primer set for extension phase
building kMer table for extension phase
removed 4777974 kMers from kMerTable
finished building kMer tables: 2179555 32-mers; 31446237 kMer pairs over 11 pair lengths
cleaned 143958/143983 starting reads
extended 47517/47844 short starting reads
141447 reads starting with F primer after extension
added 39900 starting reads

**Comment by PaulGreenfieldOz** [comment]
Scaling issues fixed in Kelpie_v2. Problem reported here came from amplicon spike-ins leading to very high depths (400K) and denoising wasn't adequately removing PCR/sequencing errors for such extremely deep reads.
