### ISSUE TITLE
Input Format-Zipped

### ISSUE THREAD

**Issue by AllisonStander** [PaulGreenfieldOz/WorkingDogs#8]
Hi there,

I am considering using Blue to error correct my Illumina paired-end data. The total size of my data is in total 320 GB zipped (fastq.gz). 

**Does Blue accept zipped files as input?**

Thank you for your time.

Kind regards,
Allison

**Comment by PaulGreenfieldOz** [comment]
Hi Allison,

No. At this point is doesn't. I'll consider adding this feature in V2.1 though. Zipping and unzipping is always a problem for me as it just takes so long, and is often the slowest part of my pipelines. 

regards,
Paul
